version: '3.8'

services:
  ytlantern:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: ytlantern
    ports:
      - "${PORT:-8080}:8080"
    environment:
      - NODE_ENV=production
      - PORT=8080
      - HOST=0.0.0.0
      - CORS_ORIGINS=http://localhost:8080,https://yourdomain.com
    volumes:
      - ./tmp:/app/tmp
      - ./server/cookies.txt:/app/server/cookies.txt:ro
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    deploy:
      resources:
        limits:
          memory: 2G
          cpus: '1.0'
        reservations:
          memory: 512M
          cpus: '0.5'

volumes:
  tmp_data:
    driver: local

networks:
  default:
    name: ytlantern-network
